'''
Create a program that will play the “cows and bulls” game
with the user. The game works like this:

Randomly generate a 4-digit number.

Ask the user to guess a 4-digit number.

For every digit that the user guessed correctly in the wrong place,
they have a “cow”.

For every digit the user guessed correctly in the right place is a “bull.”

Every time the user makes a guess, tell them how many “cows”
and “bulls” they have.

Once the user guesses the correct number, the game is over.

Keep track of the number of guesses the user makes
throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
1234
  2 cows, 0 bulls
1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''
import random

def generateNumber():
    number = ''
    for i in range(1,5):
        randString = str(random.randint(1,9))
        number = number + randString
    return number

def checkBulls(userNumber, computerNumber):
    bullCow = [0, 0]
    for char in range(0,4):
        if(userNumber[char] in computerNumber):
            if userNumber[char] == computerNumber[char]:
                bullCow[0] += 1
            else:
                bullCow[1] += 1
    return bullCow


def parseInput():
    uInput = input('>> ')
    if uInput.isdigit() and len(uInput)==4:
        return uInput
    else:
        print('not a valid number.')
        return False

if __name__ == '__main__':
    print("I will come up with a four digit number. You guess the",
          "number. Every digit you guess correctly in the wrong",
          "place is a cow. Every digit you guess correctly in ",
          "the right place is a bull.")
    computerNumber = generateNumber()
    guesses = 0
    while True:
        myNumber = parseInput()
        while myNumber == False:
            myNumber = parseInput()
        bulls = checkBulls(myNumber, computerNumber)
        print('bulls', bulls[0])
        print('cows', bulls[1])
        guesses += 1
        print('guesses', guesses)
        if bulls[0] == 4:
            print('the number was,', computerNumber)
            print('you won!')
            exit(0)
